# Generated by Django 5.1.3 on 2024-11-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tua_app', '0002_alter_job_options_alter_job_price_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jobs_images/', verbose_name='Изображение'),
        ),
    ]
